In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3,4]])

In [4]:
arr[0,2]

3

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
ar = np.array(x)

In [10]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print(ar.sum(axis=0))
print(ar.sum(axis=1))

[12 15 18]
[ 6 15 24]


In [14]:
# transposeing the array

ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
# ar.flat
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [19]:
ar.ndim

2

In [22]:
ar.argmax()

8

In [23]:
ar.shape

(3, 3)

In [26]:
ar.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [27]:
import sys

In [29]:
py_ar = [1,2,3,4]

In [32]:
np_ar = np.array(py_ar)

In [33]:
sys.getsizeof(1) * len(py_ar)

112

In [34]:
np_ar.itemsize * np_ar.size

16

### Pandas ###

In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.DataFrame(np.random.rand(300,5))

In [11]:
df.isnull().head()

0      1      2      3      4
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False